import { Nunito } from 'next/font/google';
import './globals.css';
import ClientOnly from './components/ClientOnly';
import Navbar from './components/Navbar/index';
import RegisterModal from './components/Modal/RegisterModal';
import ToasterProvider from './providers/ToasterProvider';
import LoginModal from './components/Modal/LoginModal';

export const metadata = {
   title: 'AirB',
   description: 'Generated by An',
};
const font = Nunito({
   subsets: ['latin'],
});
export default function RootLayout({
   children,
}: {
   children: React.ReactNode;
}) {
   return (
      <html lang="en">
         <body className={font.className}>
            <ClientOnly>
               <ToasterProvider />
               <LoginModal />
               <RegisterModal />
               <Navbar />
            </ClientOnly>
            {children}
         </body>
      </html>
   );
}
