import { Nunito } from 'next/font/google';
import './globals.css';
import ClientOnly from './components/ClientOnly';
import Navbar from './components/Navbar/index';
import RegisterModal from './components/RegisterModal';


export const metadata = {
   title: 'AirB',
   description: 'Generated by An',
};
const font = Nunito({
   subsets: ['latin'],
});
export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body className={font.className}>
            <ClientOnly>
               <RegisterModal/>
               <Navbar />
            </ClientOnly>
            {children}
         </body>
      </html>
   );
}
